[tool.poetry]
name = "MonitorBoss"
version = "2024.03.24"
description = "Boss your monitors around"
authors = [
    "Seizure <https://github.com/Seizure>",
    "Rangi <https://github.com/Rangi42>"
]
readme = "README.md"
license = "LGPL-3.0-only"
packages = [{include = "monitorboss"}]

[tool.poetry.dependencies]
python = "^3.10,<3.13"
tomlkit = "^0.12.4"
pyudev = {version = "^0.24.1", platform = "linux"}


[tool.poetry.group.mccs.dependencies]
pyudev = { version = ">=0.23,<0.25", platform = "linux" }
cython = {version = "^3.0.10", platform = "macos"}

[tool.poetry.group.build.dependencies]
pyinstaller = "^6.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


