[tool.poetry]
name = "MonitorBoss"
version = "2024.03.24"
description = "Boss your monitors around"
authors = [
    "Seizure <https://github.com/Seizure>",
    "Rangi <https://github.com/Rangi42>"
]
readme = "README.md"
license = "LGPL-3.0-only"
packages = [{include = "monitorboss"}]

[tool.poetry.dependencies]
python = "^3.10,<3.13"
tomlkit = "^0.12.4"

[tool.poetry.group.mccs.dependencies]
pyudev = { version = ">=0.23,<0.25", markers = "sys_platform != 'win32'" }

[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.5.0"
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


