[monitor_names]
0 = "main"

[input_names]
27 = ["usbc", "usb_c", "usb-c"] # 27 seems to be the "standard non-standard" ID for USB-C among manufacturers

[settings]
wait_get = 0.05
wait_set = 0.10
wait_internal = 0.04 # 40ms is standard; configured value does not apply on Windows
