[monitor_names]
main = 0
# Seizure's configuration
right = 2
middle = 0
left = 1

[input_names]
USBC = 27 # 27 seems to be the "standard non-standard" ID for USB-C among manufacturers

[settings]
wait = 0.05
