name: "Continuous build"
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install PyInstaller
        shell: pwsh
        run: |
          pip install pyinstaller
      - name: Build MonitorBoss
        shell: pwsh
        run: |
          ./build.ps1
      - name: Upload monitorboss.exe
        uses: actions/upload-artifact@v4
        with:
          name: monitorboss.exe
          path: dist/monitorboss.exe