name: "Rolling release"
on:
  push:
    branches:
      - master
env:
  RELEASE_TAG: "rolling-release"
jobs:
  build:
    name: "Continuous build"
    uses: Seizure/MonitorBoss/.github/workflows/build.yml@master
  release:
    runs-on: windows-2022
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Download monitorboss.exe
        uses: actions/download-artifact@v3
        with:
          name: monitorboss.exe
          path: dist/monitorboss.exe
      - name: Delete old release
        uses: cb80/delrel@latest
        with:
          tag: ${{ env.RELEASE_TAG }}
      - name: Advance release tag to master
        run: |
          git tag ${{ env.RELEASE_TAG }} -f
          git push --tags -f "https://Seizure:$GITHUB_TOKEN@github.com/Seizure/MonitorBoss.git"
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Rolling release
          body: |
            This is a rolling release build of the master branch of MonitorBoss.
          draft: false
          prerelease: false
      - name: Upload monitorboss.exe
        id: upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: |
            ./monitorboss.exe